using Bunit;
using ExperimentFramework.Dashboard.UI.Components.Pages;
using ExperimentFramework.Dashboard.UI.Services;
using Microsoft.Extensions.DependencyInjection;
using System.Net;
using System.Net.Http.Json;

namespace ExperimentFramework.Dashboard.UI.Tests.Components;

/// <summary>
/// bUnit tests that exercise async @code paths.
///
/// Pages without @rendermode InteractiveServer (Analytics, Targeting, HypothesisTesting)
/// call OnInitializedAsync unconditionally, so these tests exercise async state machines
/// simply by rendering the component.
///
/// Pages with @rendermode InteractiveServer (Experiments, Rollout) require
/// SetRendererInfo(isInteractive: true) to trigger data loading.
///
/// The async state-machine classes generated by the C# compiler for async @code methods
/// are instrumented when CompilerGeneratedAttribute is NOT in ExcludeByAttribute —
/// see tests/ExperimentFramework.Dashboard.UI.Tests/coverage.runsettings.
/// </summary>
public sealed class InteractiveComponentTests : BunitContext
{
    // =========================================================
    // URL constants (all relative to base http://localhost/)
    // =========================================================
    private const string ExperimentsUrl = "/api/experiments";
    private const string UsageStatsUrl = "/api/analytics/usage";
    private const string AuditLogUrl = "/api/audit";
    private const string KillSwitchUrl = "/api/configuration/kill-switch";

    // =========================================================
    // Shared helpers
    // =========================================================

    private static ExperimentApiClient BuildApiClient(MultiEndpointHandler handler)
        => new ExperimentApiClient(new HttpClient(handler) { BaseAddress = new Uri("http://localhost/") });

    private static ExperimentInfo MakeExperiment(string name = "exp-1", string status = "Active")
        => new ExperimentInfo
        {
            Name = name,
            DisplayName = name,
            Description = "Test experiment",
            Status = status,
            Category = "Revenue",
            Variants = new List<VariantInfo>
            {
                new VariantInfo { Name = "control", DisplayName = "Control" },
                new VariantInfo { Name = "variant-a", DisplayName = "Variant A" },
            },
            TargetingRules = new List<TargetingRule>(),
        };

    private static HttpResponseMessage JsonOk<T>(T value)
        => new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = JsonContent.Create(value)
        };

    // =========================================================
    // Analytics page tests (no rendermode guard — async runs always)
    // =========================================================

    [Fact]
    public async Task Analytics_OnInitializedAsync_CallsGetUsageStats()
    {
        var called = false;
        var handler = new MultiEndpointHandler();
        handler.Add(UsageStatsUrl, _ =>
        {
            called = true;
            return JsonOk(new Dictionary<string, Dictionary<string, int>>
            {
                ["exp-1"] = new Dictionary<string, int> { ["control"] = 100, ["variant"] = 90 }
            });
        });
        handler.Add(AuditLogUrl, _ => JsonOk(new List<object>()));

        Services.AddSingleton(BuildApiClient(handler));

        Render<Analytics>();

        // The analytics page calls OnInitializedAsync which calls GetUsageStatsAsync synchronously
        // in bUnit's test renderer — we poll with small delay for async operations
        await Task.Delay(200);

        Assert.True(called, "GetUsageStatsAsync should be called during OnInitializedAsync");
    }

    [Fact]
    public async Task Analytics_WhenApiReturnsData_RendersPage()
    {
        var handler = new MultiEndpointHandler();
        handler.Add(UsageStatsUrl, _ =>
            JsonOk(new Dictionary<string, Dictionary<string, int>>
            {
                ["pricing-strategy"] = new Dictionary<string, int> { ["control"] = 50, ["variant"] = 45 }
            }));
        handler.Add(AuditLogUrl, _ => JsonOk(new List<object>()));

        Services.AddSingleton(BuildApiClient(handler));

        var cut = Render<Analytics>();
        await Task.Delay(200);
        cut.Render();

        Assert.NotNull(cut.Find("main[data-page='analytics']"));
    }

    [Fact]
    public async Task Analytics_WhenApiThrows_HandlesGracefully()
    {
        var handler = new MultiEndpointHandler();
        handler.Add(UsageStatsUrl, _ => new HttpResponseMessage(HttpStatusCode.InternalServerError));
        handler.Add(AuditLogUrl, _ => new HttpResponseMessage(HttpStatusCode.InternalServerError));

        Services.AddSingleton(BuildApiClient(handler));

        var cut = Render<Analytics>();
        await Task.Delay(200);

        Assert.NotNull(cut.Find("main[data-page='analytics']"));
    }

    [Fact]
    public async Task Analytics_WhenApiReturnsEmpty_DoesNotCrash()
    {
        var handler = new MultiEndpointHandler();
        handler.Add(UsageStatsUrl, _ => JsonOk(new Dictionary<string, Dictionary<string, int>>()));
        handler.Add(AuditLogUrl, _ => JsonOk(new List<object>()));

        Services.AddSingleton(BuildApiClient(handler));

        var cut = Render<Analytics>();
        await Task.Delay(200);
        cut.Render();

        Assert.NotNull(cut.Find("main[data-page='analytics']"));
    }

    [Fact]
    public async Task Analytics_WithMultipleExperiments_RendersData()
    {
        var handler = new MultiEndpointHandler();
        handler.Add(UsageStatsUrl, _ =>
            JsonOk(new Dictionary<string, Dictionary<string, int>>
            {
                ["pricing-strategy"] = new Dictionary<string, int> { ["control"] = 50, ["variant"] = 45 },
                ["notification-style"] = new Dictionary<string, int> { ["control"] = 30, ["variant"] = 35 },
            }));
        handler.Add(AuditLogUrl, _ => JsonOk(new List<AuditLogEntry>
        {
            new AuditLogEntry { ExperimentName = "pricing-strategy", EventType = "selection", TrialName = "control", Timestamp = DateTime.UtcNow.AddMinutes(-5) },
        }));

        Services.AddSingleton(BuildApiClient(handler));

        var cut = Render<Analytics>();
        await Task.Delay(200);
        cut.Render();

        Assert.NotNull(cut.Find("main[data-page='analytics']"));
    }

    // =========================================================
    // Targeting page tests (no rendermode guard)
    // =========================================================

    [Fact]
    public async Task Targeting_OnInitializedAsync_CallsGetExperiments()
    {
        var called = false;
        var handler = new MultiEndpointHandler();
        handler.Add(ExperimentsUrl, _ =>
        {
            called = true;
            return JsonOk(new { experiments = new List<ExperimentInfo> { MakeExperiment() } });
        });

        Services.AddSingleton(BuildApiClient(handler));

        Render<Targeting>();
        await Task.Delay(200);

        Assert.True(called, "GetExperimentsAsync should be called during OnInitializedAsync");
    }

    [Fact]
    public async Task Targeting_WhenLoaded_RendersPage()
    {
        var handler = new MultiEndpointHandler();
        handler.Add(ExperimentsUrl, _ => JsonOk(new { experiments = new List<ExperimentInfo>() }));

        Services.AddSingleton(BuildApiClient(handler));

        var cut = Render<Targeting>();
        await Task.Delay(200);
        cut.Render();

        Assert.NotNull(cut.Find("main[data-page='targeting']"));
    }

    [Fact]
    public async Task Targeting_WhenApiThrows_HandlesGracefully()
    {
        var handler = new MultiEndpointHandler();
        handler.Add(ExperimentsUrl, _ => new HttpResponseMessage(HttpStatusCode.ServiceUnavailable));

        Services.AddSingleton(BuildApiClient(handler));

        var cut = Render<Targeting>();
        await Task.Delay(200);

        Assert.NotNull(cut.Find("main[data-page='targeting']"));
    }

    [Fact]
    public async Task Targeting_WithExperimentsHavingTargetingRules_RendersTargetingData()
    {
        var exp = MakeExperiment("my-exp");
        exp.TargetingRules = new List<TargetingRule>
        {
            new TargetingRule
            {
                Name = "region-rule",
                Variant = "variant-a",
                Conditions = new List<TargetingCondition>
                {
                    new TargetingCondition { Attribute = "region", Operator = "equals", Value = "us-east" }
                }
            }
        };

        var handler = new MultiEndpointHandler();
        handler.Add(ExperimentsUrl, _ =>
            JsonOk(new { experiments = new List<ExperimentInfo> { exp } }));

        Services.AddSingleton(BuildApiClient(handler));

        var cut = Render<Targeting>();
        await Task.Delay(200);
        cut.Render();

        Assert.NotNull(cut.Find("main[data-page='targeting']"));
    }

    // =========================================================
    // Experiments page with isInteractive: true
    // =========================================================

    [Fact]
    public async Task Experiments_WithIsInteractiveTrue_CallsLoadExperiments()
    {
        var called = false;
        var handler = new MultiEndpointHandler();
        handler.Add(ExperimentsUrl, _ =>
        {
            called = true;
            return JsonOk(new { experiments = new List<ExperimentInfo>() });
        });
        handler.Add(KillSwitchUrl, _ => JsonOk(new List<object>()));

        Services.AddSingleton(BuildApiClient(handler));
        Services.AddSingleton<DashboardStateService>();
        Services.AddSingleton<ThemeService>();
        SetRendererInfo(new Microsoft.AspNetCore.Components.RendererInfo("Server", isInteractive: true));

        Render<Experiments>();
        await Task.Delay(200);

        Assert.True(called, "LoadExperiments should be called when isInteractive=true");
    }

    [Fact]
    public async Task Experiments_WithIsInteractiveTrue_RendersExperimentList()
    {
        var experiments = new List<ExperimentInfo>
        {
            MakeExperiment("exp-1", "Active"),
            MakeExperiment("exp-2", "Paused"),
        };

        var handler = new MultiEndpointHandler();
        handler.Add(ExperimentsUrl, _ => JsonOk(new { experiments }));
        handler.Add(KillSwitchUrl, _ => JsonOk(new List<object>()));

        Services.AddSingleton(BuildApiClient(handler));
        Services.AddSingleton<DashboardStateService>();
        Services.AddSingleton<ThemeService>();
        SetRendererInfo(new Microsoft.AspNetCore.Components.RendererInfo("Server", isInteractive: true));

        var cut = Render<Experiments>();
        await Task.Delay(200);
        cut.Render();

        Assert.NotNull(cut.Find("main[data-page='experiments']"));
    }

    [Fact]
    public async Task Experiments_WithIsInteractiveTrue_WhenApiThrows_RendersPageWithError()
    {
        var handler = new MultiEndpointHandler();
        handler.Add(ExperimentsUrl, _ => new HttpResponseMessage(HttpStatusCode.InternalServerError));
        handler.Add(KillSwitchUrl, _ => JsonOk(new List<object>()));

        Services.AddSingleton(BuildApiClient(handler));
        Services.AddSingleton<DashboardStateService>();
        Services.AddSingleton<ThemeService>();
        SetRendererInfo(new Microsoft.AspNetCore.Components.RendererInfo("Server", isInteractive: true));

        var cut = Render<Experiments>();
        await Task.Delay(200);
        cut.Render();

        // Page structure must exist even on error
        Assert.NotNull(cut.Find("main[data-page='experiments']"));
    }

    [Fact]
    public async Task Experiments_FilterByCategory_UpdatesState()
    {
        var handler = new MultiEndpointHandler();
        handler.Add(ExperimentsUrl, _ => JsonOk(new { experiments = new List<ExperimentInfo>() }));
        handler.Add(KillSwitchUrl, _ => JsonOk(new List<object>()));

        var dashState = new DashboardStateService();
        Services.AddSingleton(BuildApiClient(handler));
        Services.AddSingleton(dashState);
        Services.AddSingleton<ThemeService>();
        SetRendererInfo(new Microsoft.AspNetCore.Components.RendererInfo("Server", isInteractive: true));

        var cut = Render<Experiments>();
        await Task.Delay(200);
        cut.Render();

        // Click a category filter button
        var revenueBtn = cut.Find(".category-btn[data-category='Revenue']");
        await cut.InvokeAsync(() => revenueBtn.Click());

        Assert.Equal("Revenue", dashState.ExperimentFilterCategory);
    }

    [Fact]
    public async Task Experiments_ClickAllFilter_ClearsCategory()
    {
        var handler = new MultiEndpointHandler();
        handler.Add(ExperimentsUrl, _ => JsonOk(new { experiments = new List<ExperimentInfo>() }));
        handler.Add(KillSwitchUrl, _ => JsonOk(new List<object>()));

        var dashState = new DashboardStateService();
        dashState.ExperimentFilterCategory = "Revenue";
        Services.AddSingleton(BuildApiClient(handler));
        Services.AddSingleton(dashState);
        Services.AddSingleton<ThemeService>();
        SetRendererInfo(new Microsoft.AspNetCore.Components.RendererInfo("Server", isInteractive: true));

        var cut = Render<Experiments>();
        await Task.Delay(200);
        cut.Render();

        var allBtn = cut.Find(".category-btn[data-category='All']");
        await cut.InvokeAsync(() => allBtn.Click());

        Assert.Null(dashState.ExperimentFilterCategory);
    }

    [Fact]
    public async Task Experiments_WithIsInteractiveTrue_WithExperiments_CountsVariants()
    {
        var experiments = new List<ExperimentInfo>
        {
            MakeExperiment("exp-1", "Active"),
        };

        var handler = new MultiEndpointHandler();
        handler.Add(ExperimentsUrl, _ => JsonOk(new { experiments }));
        handler.Add(KillSwitchUrl, _ => JsonOk(new List<object>()));

        Services.AddSingleton(BuildApiClient(handler));
        Services.AddSingleton<DashboardStateService>();
        Services.AddSingleton<ThemeService>();
        SetRendererInfo(new Microsoft.AspNetCore.Components.RendererInfo("Server", isInteractive: true));

        var cut = Render<Experiments>();
        await Task.Delay(200);
        cut.Render();

        // Stats row should be present
        var statCards = cut.FindAll(".stat-card");
        Assert.Equal(4, statCards.Count);
    }

    // =========================================================
    // HypothesisTesting page (no rendermode guard)
    // =========================================================

    [Fact]
    public async Task HypothesisTesting_OnInitializedAsync_CallsGetExperiments()
    {
        var called = false;
        var handler = new MultiEndpointHandler();
        handler.Add(ExperimentsUrl, _ =>
        {
            called = true;
            return JsonOk(new { experiments = new List<ExperimentInfo>() });
        });

        Services.AddSingleton(BuildApiClient(handler));

        Render<HypothesisTesting>();
        await Task.Delay(200);

        Assert.True(called, "GetExperimentsAsync should be called during OnInitializedAsync");
    }

    [Fact]
    public async Task HypothesisTesting_WhenLoaded_RendersPage()
    {
        var handler = new MultiEndpointHandler();
        handler.Add(ExperimentsUrl, _ =>
            JsonOk(new { experiments = new List<ExperimentInfo> { MakeExperiment() } }));

        Services.AddSingleton(BuildApiClient(handler));

        var cut = Render<HypothesisTesting>();
        await Task.Delay(200);
        cut.Render();

        Assert.NotNull(cut.Find("main[data-page='hypothesis']"));
    }

    [Fact]
    public async Task HypothesisTesting_WhenApiThrows_HandlesGracefully()
    {
        var handler = new MultiEndpointHandler();
        handler.Add(ExperimentsUrl, _ =>
            new HttpResponseMessage(HttpStatusCode.InternalServerError));

        Services.AddSingleton(BuildApiClient(handler));

        var cut = Render<HypothesisTesting>();
        await Task.Delay(200);

        Assert.NotNull(cut.Find("main[data-page='hypothesis']"));
    }

    [Fact]
    public async Task HypothesisTesting_WithExperimentsLoaded_SeedsHypotheses()
    {
        var experiments = new List<ExperimentInfo>
        {
            MakeExperiment("pricing-strategy", "Active"),
            MakeExperiment("notification-style", "Active"),
            MakeExperiment("recommendation-algorithm", "Active"),
        };

        var handler = new MultiEndpointHandler();
        handler.Add(ExperimentsUrl, _ => JsonOk(new { experiments }));

        Services.AddSingleton(BuildApiClient(handler));

        var cut = Render<HypothesisTesting>();
        await Task.Delay(200);
        cut.Render();

        // After init, experiments are loaded and hypotheses are seeded
        Assert.NotNull(cut.Find("main[data-page='hypothesis']"));
    }

    // =========================================================
    // Utility types
    // =========================================================

    private sealed class MultiEndpointHandler : HttpMessageHandler
    {
        private readonly List<(string Path, Func<HttpRequestMessage, HttpResponseMessage> Handler)> _routes = new();

        public void Add(string pathPrefix, Func<HttpRequestMessage, HttpResponseMessage> handler)
            => _routes.Add((pathPrefix, handler));

        protected override Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request,
            CancellationToken cancellationToken)
        {
            var path = request.RequestUri?.PathAndQuery ?? "";
            foreach (var (prefix, handler) in _routes)
            {
                if (path.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                    return Task.FromResult(handler(request));
            }
            // Default: empty 200 OK
            return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent("{}", System.Text.Encoding.UTF8, "application/json")
            });
        }
    }
}
